config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  resources :home
  get "users/sign_in", to: "sessions#new"
  post "users/sign_in", to: "sessions#create"
  get "users/show", to: "users#show"

  get "owners/sign_in", to: "sessions#new"
  get "/owners/show_to_owner", to: "owners#show_to_owner"
  get "/owners/showmenu", to: "owners#show_menu"
  get "/owners/addmenu", to: "owners#addmenu"
  post "owners/sign_in", to: "sessions#create"

  get "users/delete_user", to: "owners#delete_user"
  delete "users/destroy", to: "users#destroy"

  get "users/update_user", to: "owners#update_user"
  put "users/update", to: "users#update"

  put "carts/addq/", to: "carts#addq"
  put "carts/removeq", to: "carts#removeq"

  post "/order_items/create", to: "order_items#create"

  put "/order_items/update", to: "order_items#update"

  post "/menu_category/create", to: "menu_category#create"

  resources :carts
  resources :orders
  resources :order_items
  resources :menu_category
  resources :submenu_items
  resources :users
  resources :owners

  delete "logout", to: "sessions#destroy"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li class="nav-item">
            <%= link_to "Home","/" , class:"nav-link" %>
            </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
               <% if session[:current_user_id] || session[:current_owner_id]  %>
                          <% role = session[:current_user_id].present? ? @user : @owner %>
                          <% if role.present? && role.role == "User" %>
                                 <li class="nav-item">
                                    <%= link_to "My Orders",  order_items_path + "/" +  session[:current_user_id].to_s , class:"btn btn-dark", method:"get" %>
                                </li>
                          <% end %>

                          <li class="nav-item">
                              <span class="navbar-text"> <%= role.first_name %></span>
                          </li>
                          <li class="nav-item">
                            <%= button_to "Logout", logout_path, class:"btn btn-danger", method:"delete" %>
                          </li>
                  </ul>
            <% else %>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Sign-Up", "/users/new", class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log-In", "/users/sign_in", class:"nav-link" %>
                </li>
            </ul>
            <% end %>
      </div>
  </div>
</nav>